### ISSUE TITLE
NSIS ?

### ISSUE THREAD

**Issue by ramstein74** [bradstewart/electron-boilerplate-vue#12]
any ideas?
i tried npm run release and got an error...

![image](https://cloud.githubusercontent.com/assets/1210858/14061839/c92984a8-f382-11e5-8f1e-a40c9ce5313d.png)

**Comment by bradstewart** [comment]
Hi @ramstein74, installing http://nsis.sourceforge.net/Main_Page should resolve that issue (it looks your on windows, so it should work fine). NSIS is used to generate the actual Windows installers. 

Just an FYI, I recently overhauled the entire project. There's nothing truly wrong with the previous setup, but tried to simplify the build setup, added hot-reload support, and improved test execution. It's currently missing the functionality to generate installers, but I will be adding it back soon (once https://github.com/electron-userland/electron-packager stabilizes). It will use Squirrel rather NSIS.

**Comment by ramstein74** [comment]
i solved the NSIS but got this next error.
It says 
Installer ready at the end but an error in line before...
![image](https://cloud.githubusercontent.com/assets/1210858/14090968/43e3f378-f535-11e5-9f04-b5a50d205fdd.png)
any ideas?

**Comment by bradstewart** [comment]
What version of NSIS did you install? I believe only 3+ supports Unicode. You can simple comment out/remove L31 of `resources/windows/installer.nsi` as well if you don't need Unicode support.

**Comment by ramstein74** [comment]
solved that and another error. can you help ?
![image](https://cloud.githubusercontent.com/assets/1210858/14172248/05f24ece-f72f-11e5-81f5-c39e5beaba0b.png)

**Comment by bradstewart** [comment]
It looks like it's failing to build a native dependency for some reason. It doesn't appear to be an issue with this project specifically, can you confirm other native packages compile without issue on your machine? I don't have a Windows machine handy, so there's not much I can do.
