### ISSUE TITLE
not compatible wth os or architecture ?!?!?

### ISSUE THREAD

**Issue by ramstein74** [bradstewart/electron-boilerplate-vue#13]
![image](https://cloud.githubusercontent.com/assets/1210858/14139791/0fb3b0fa-f66d-11e5-97b8-7ec6035b06cf.png)

this error was on a 64bits windows 7

**Comment by bradstewart** [comment]
It appears to be an issue with npm which has been fixed in 3.7.0, see https://github.com/npm/npm/issues/10768#issuecomment-186828108. If updating npm does not resolve this, feel free to reopen.
