### ISSUE TITLE
Problem with npm run build

### ISSUE THREAD

**Issue by dbalas** [bradstewart/electron-boilerplate-vue#15]
Currently It's `"build": "rimraf dist && mkdirp dist cross-env NODE_ENV=production webpack --progress --hide-modules --config build/webpack.prod.conf.js",` so mkdirp create cross-env, NODE_ENV=production and webpack folders.
But it should be: `rimraf dist && mkdirp dist && cross-env NODE_ENV=production webpack --progress --hide-modules --config build/webpack.prod.conf.js` no?

**Comment by bradstewart** [comment]
Oh wow, you are absolutely right--not sure how I managed that one. Thanks for the heads up! Fixed in https://github.com/bradstewart/electron-boilerplate-vue/commit/aabbc0c21cd53f1bc97aac051fb06a055440101a

**Comment by dbalas** [comment]
you're welcome, nice repo and good job!
