### ISSUE TITLE
release on windows

### ISSUE THREAD

**Issue by ramstein74** [bradstewart/electron-boilerplate-vue#16]
hi i cannot do 
npm run release ( windows 7 64bts)
can you help ?
Thank you
i get this error
![image](https://cloud.githubusercontent.com/assets/1210858/14291900/7af05c0c-fb5d-11e5-94f3-0f2c3ba5b522.png)

**Comment by bradstewart** [comment]
Fixed in https://github.com/bradstewart/electron-boilerplate-vue/commit/e655be00d21bb04a2ed8a0e61522e5550b5394b2. Sorry about that.
