### ISSUE TITLE
same module i use in app/  and build/  where package.json i put ?

### ISSUE THREAD

**Issue by xiaokaike** [bradstewart/electron-boilerplate-vue#23]
i use express in build script   dev-server.js
and 
use express in app/ electron app 

then i put the `express` in the outside package.json  like

``` json
devDependencies:{
"express": "^4.13.3",
...
```

and i also put the `express` in app/package.json

``` json
dependencies:{
"express": "^4.13.3",
...
```

when i run `npm run start` then i  get a warning

``` bash
WARNING in ./app/~/express/lib/view.js
            Critical dependencies:
            78:29-56 the request of a dependency is an expression
             @ ./app/~/express/lib/view.js 78:29-56
```

How can I solve this warning

**Comment by bradstewart** [comment]
@xiaokaike I think this  has something to do with webpack rather than the having `express` in both packages. Try adding `express` as an external to prevent webpack from compiling it (which is what we want since it will ship with the app):

``` javascript
// build/webpack.base.conf.js 
...
plugins: [
    new webpack.ExternalsPlugin('commonjs2', [
      ...
      'screen',
      'shell',
      'express' // <-- Add this line.
    ])
  ],
...
```

**Comment by xiaokaike** [comment]
@bradstewart  thanks  close the issue
