### ISSUE TITLE
Accessing app node_modules folder from html

### ISSUE THREAD

**Issue by ElMatella** [bradstewart/electron-boilerplate-vue#38]
Hi, 

I am trying to use Bootstrap, so I ran `npm install --save bootstrap` into the `app` folder. However, I can't find how to reach the `app/node_modules` folder from my HTML. I tried the following:

```
./node_modules/bootstrap/dist/css/bootstrap.min.css
/node_modules/bootstrap/dist/css/bootstrap.min.css
node_modules/bootstrap/dist/css/bootstrap.min.css
```

Am I missing the point of the `app/package.json` file? By default, jQuery is present in the dependencies of this package, how and where should I use the jQuery present in this `package.json` file?

**Comment by matteodem** [comment]
Did you find a solution to this? Facing the same problem right now

**Comment by ElMatella** [comment]
I ended up importing bootstrap from js: 

```
import 'bootstrap/dist/css/bootstrap.min.css'
```
