### ISSUE TITLE
external css files are not compiled?

### ISSUE THREAD

**Issue by thalesrca** [bradstewart/electron-boilerplate-vue#43]
I'm having problem with css files location inside the project. 

For now, the only way I get it working was placing them in the static directory.

I would like to know if there's a way to place them inside the assets directory (like: "assets/css") and when builded, they get compiled to app.css (to where the vuejs components css are compiled).

Thanks!

**Comment by bradstewart** [comment]
Files in `app/assets` will be compiled by webpack, assuming they are referenced by the entry file. If `require('./app/assets/css/style')` in `main.js` or `App.vue` doesn't work for you (it does for me), let me know.
