### ISSUE TITLE
update to Vue.js version 2.0

### ISSUE THREAD

**Issue by motorcityadam** [bradstewart/electron-boilerplate-vue#46]
As you may be aware, Vue.js version 2.0 was just released which saw several improvements and nice features added (see https://medium.com/the-vue-point/vue-2-0-is-here-ef1f26acf4b8#.nbs1x41ow). It would be nice to update this project to use the updated version of Vue.js. Thoughts?

**Comment by AugustBurnsRed** [comment]
The update is quite easy. Just update vue with npm and in main.js switch the components line with: render: h => h(App)

**Comment by bondydaa** [comment]
I was able to upgrade to vue 2.x by updating the `vue` package in `package.json` in the root and added the following after the plugins section of `build/webpack.dev-main.conf.js`

```
resolve: {
    alias: {vue: 'vue/dist/vue.js'}
  }
```

Though now I'm not seeing any styles being loaded into my app, I'm going to create a separate issue as I'm a bit lost as to what would be causing this... whether it is vue-loader, vue-style-loader, webpack, or something completely different.

**Comment by AugustBurnsRed** [comment]
I have the same problem with the styles.

**Comment by bondydaa** [comment]
I created this issue for the style not rending issue - #48

**Comment by bradstewart** [comment]
Will do this as part of #50. Feel free to add any other thoughts, problems, etc. there.
