### ISSUE TITLE
Parsing errors on default files after install

### ISSUE THREAD

**Issue by lukkor** [bradstewart/electron-boilerplate-vue#7]
Hello,

After fresh install, I've several parsing errors on default files of the boilerplate but, strangely, the application runs normally.

```
ERROR in ./app/app.js

/home/ludovic/projects/elecnote/app/app.js
  6:2  error  Parsing error: Illegal import declaration

✖ 1 problem (1 error, 0 warnings)


ERROR in ./app/hello_world/hello_world.js

/home/ludovic/projects/elecnote/app/hello_world/hello_world.js
  1:2  error  Parsing error: Illegal export declaration

✖ 1 problem (1 error, 0 warnings)


ERROR in ./app/~/babel-loader!./~/eslint-loader!./app/~/vue-loader/lib/selector.js?type=script&index=0!./app/components/HelloWorld.vue

/home/ludovic/projects/elecnote/app/components/HelloWorld.vue
  1:2  error  Parsing error: Unexpected token const

✖ 1 problem (1 error, 0 warnings)
```

Is it a problem for dev and/or futur application ? What can I do to fix these errors ?

Thanks for your boilerplate, it is really helpful :+1:
Ludovic

**Comment by bradstewart** [comment]
@Lukkor I can't seem to reproduce this. What version of node and npm are you using?

**Comment by lukkor** [comment]
I need to update nodejs and npm:
npm: 1.3.10
node: v0.10.25

I'll check later if it solves the problem.
Thanks @bradstewart

**Comment by bradstewart** [comment]
I should update package.json to indicate this, but I believe using node 5 will resolve the issue. Let me know what happens.
